config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  match '/about_us', to: 'static_pages#about_us', via: 'get'
  match '/idea', to: 'static_pages#idea', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :tasks
  resources :users

  resources :sessions, only: [:new, :create, :destroy]

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	before_save {self.email = email.downcase}
	before_create :create_remember_token

	validates :name, presence:true, length: {maximum:30}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	
	has_many :tasks

	has_secure_password
	validates :password, length: {maximum:30, minimum:6}


	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

	def User.encrypt(token)
	   	Digest::SHA1.hexdigest(token.to_s)
	end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		  if user && user.authenticate(params[:session][:password])
		  	sign_in user
      		redirect_to user
		  else
		    flash[:error] = 'Invalid email/password combination' # Not quite right!
      		render 'new'
		  end
	end

	def destroy
    	sign_out
    	redirect_to root_url
  	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about_us
  end

  def idea
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:user_id, :color, :start_time, :end_time)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
    base_title = "Manipulating Time Inc."
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
                <nav id="menu">
                        <ul>
                            <li><%= link_to "Manipulating Time", root_path %></li>
                            <li><%= link_to "About Us", about_us_path %></li>
                            <li><%= link_to "Idea", idea_path %></li>
                        </ul>
                </nav>

                <div id="authentication">
                    <% if signed_in? %>
                        <%= link_to "#{@current_user.name}", current_user, class:'user'  %>
                        <a href="#" class="notifications"><%= image_tag('notifications.png') %></a>  
                    <% else %>
                        <%= link_to "Log In", login_path, class:'login'  %>
                        <%= link_to "Sign Up", signup_path, class:'signup'  %> 
                    <% end %>
                </div>
        </header>
        <div style="clear:both"></div>

        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about_us.html.erb
<% provide(:title, 'About Us') %>
  <%= render 'layouts/header' %> 
<h1></h1>


<section id="content">
            <h1>This is StartUp for smartWatch</h1>
               <h3>Team members:</h3>
               <h4>Leshinskiy Volodimir - Management</h4>
<h4>Kravchenko Alex - Ruby, JavaScript, HTML5, CSS3</h4>
<h4><a href="https://vk.com/sobol_kostya" target="blank">Sobol Konstantin</a> - design web-site</h4>
			
			<h1>Financials </h1>
            <p>Web hosting ~ <span style="color:green">10$</span> per month * 12 = <span style="color:green">120$</span></p>
			<p>Apple Market – <span style="color:green">25$</span> at the first time</p>
			<p>Play Market – <span style="color:green">25$</span> at the first time</p>
			<p>Amazon Web-Services ~ <span style="color:green">4$</span> per month * 12 = <span style="color:green">48$</span></p>
			<p>Total: <span style="color:green">168$</span> per year & <span style="color:green">50$</span> per mobile app markets</p>
			<p>Current balance: <span style="color:red">25$</span></p>
        </section>

        <footer>
           <p>Manipulating Time &copy; 2016</p>
        </footer>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
       <%= render 'layouts/header' %> 
        <section id="main">
            <div id="task_list">
                <ul>
                    <li><a href="#"><span class="name-task">Time to work</span>&#32;<span class="time-of-end-task">01:21:28</span></a></li>

                    <li><a href="#"><span class="name-task">Time to rest</span>&#32;<span class="time-of-end-task">01:21:28</span></a></li>

                    <li><a href="#"><span class="name-task">GYM</span>&#32;<span class="time-of-end-task">01:21:28</span></a></li>

                    <li><a href="#"><span class="name-task">Time to study</span>&#32;<span class="time-of-end-task">01:21:28</span></a></li>

                    <li><a href="#"><span class="name-task">Time to work</span>&#32;<span class="time-of-end-task">01:21:28</span></a></li>

                    <li><a href="#"><span class="name-task">Time to rest</span>&#32;<span class="time-of-end-task">01:21:28</span></a></li>

                    <li><a href="#"><span class="name-task">GYM</span>&#32;<span class="time-of-end-task">01:21:28</span></a></li>

                    <li><a href="#"><span class="name-task">Time to study YEAA</span>&#32;<span class="time-of-end-task">01:21:28</span></a></li>

                </ul>
            </div>

            <div id="watch">
                <div id="clock_view">
                    <article id="time">
                        <div id="center"></div>
                        <div id="second"></div>
                        <div id="minute"></div>
                        <div id="hour"></div> 
                    </article>
                </div>
                <div id="time_now">
                    <a href="#" class="left_arrow"></a>
                    <div id="now"></div>
                    <a href="#" class="right_arrow"></a>
                </div>
                <div style="clear:both"></div>
                <div id="time_to_next">
                    You have <span class="next">01:21:28</span> for the next time
                </div>
            </div>

            <div id="editing_task">
                <h2>Create new task</h2>
                <form id="creating_task">
                    <div>
                        <input type="text" id="task_name" name="task_name" placeholder="Name task...">
                    </div>
                    <div>
                        <input type="text" id="start_date" name="start_date" placeholder="Start time...">
                    </div>
                    <div>
                        <input type="text" id="end_date" name="end_date" placeholder="Finish time...">
                    </div>
                    <div>
                        <select size="1" name="color" id="selected_color">
                            <option value="0000ff" class="blue">Blue</option>
                            <option value="00ffff" class="cyan">Cyan</option>
                            <option value="ffffff" class="white">White</option>
                            <option value="ff00ff" class="magenta">Magenta</option>
                            <option value="800000" class="maroon">Maroon</option>
                       </select>
                    </div>
                    <div>
                        <input type="submit" value="OK">
                    </div>
                </form>
            </form>
            </div>
            <div style="clear:both"></div>
        </section>

        <footer class="footer_blue">
           <p>Manipulating Time &copy; 2016</p>
        </footer>









        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        
        <script>
            $(function() {
                $("#task_list").css("overflow", "hidden").wrapInner("<div id='mover' />");
                var $el,
                    speed = 9.2,
                    cur = -1,
                    items = $("#task_list a"),
                max = items.length - 10;
                items.each(function(i) {
                    $(this).attr("data-pos", i);
                }).hover(function() {
                    $el = $(this);
                    $el.addClass("hover");
                    $("#mover").css("top", -($el.data("pos") * speed - 0));
                    cur = $el.data("pos");
                },function() {
                    $(this).removeClass("hover");
                });
            });
        </script>


        <script type="text/javascript">
        $(document).ready(function(){
            setInterval(function() {
                $("#now").text(formatAMPM(new Date()));
            }, 1000);  
         
        });
            function formatAMPM(date) {
              var hours = date.getHours();
              var minutes = date.getMinutes();
              var seconds = date.getSeconds();
              var ampm = hours >= 12 ? 'PM' : 'AM';
              hours = hours % 12;
              hours = hours ? hours : 12; // the hour '0' should be '12'
              minutes = minutes < 10 ? '0'+minutes : minutes;
              seconds = seconds < 10 ? '0'+seconds : seconds;
              var strTime = hours + ':' + minutes + ':' + seconds + ' ' + ampm;
              return strTime;
            }
        </script>

        <script type="text/javascript">

        $(document).ready(function($) {
setInterval( function() {
      var seconds = new Date().getSeconds();
      var sdegree = seconds * 6;
      var srotate = 'rotate(' + sdegree + 'deg)';

      $('#second').css({'-moz-transform' : srotate, '-webkit-transform' : srotate, '-o-transform' : srotate});

      }, 1000 );

      setInterval( function() {
      var hours = new Date().getHours();
      var mins = new Date().getMinutes();
      var hdegree = hours * 30 + (mins / 2);
      var hrotate = 'rotate(' + hdegree + 'deg)';

      $('#hour').css({'-moz-transform' : hrotate, '-webkit-transform' : hrotate, '-o-transform' : hrotate});

      }, 1000 );

      setInterval( function() {
      var mins = new Date().getMinutes();
      var mdegree = mins * 6;
      var mrotate = 'rotate(' + mdegree + 'deg)';

      $('#minute').css({'-moz-transform' : mrotate, '-webkit-transform' : mrotate, '-o-transform' : mrotate});

      }, 1000 );
    
    
});
</script>

        

app/views/static_pages/idea.html.erb
<% provide(:title, 'Idea') %>
  <%= render 'layouts/header' %> 
<h1></h1>


<section id="content">
            <h1>This is StartUp for smartWatch</h1>
            <h1>Company Purpose</h1>
            <p>ManipulatingTime – appliacation-oriented people of any age who have smartWatch. User-friendly interface that anyone can starts own tasks for own time quickly without any troubles and problems.</p>

            <h1>Problem</h1>
            <p>The main problem is that the existing time management solutions for people with smart watches, inefficient and not friendly in terms of user interface.</p>

            <h1>Why Now</h1>
            <p>Because increasing popularity of smart watches.</p>

            <h1>Market Size </h1>
            <p>Web project covers a huge audience <span style="color:blue">(~10 000 000)</span>. I suppose that <span style="color:green">1 000$</span> will be allocated for the project within a year.</p>

            <h1>Product</h1>
            <p>Product features: synchronization (mobile, web, smartWatch), add money-services, add security-services, design many interactive pie charts</p>

            <h1>Business Model </h1>
            <p>Uniqueness of the product is that it can work with smartWatch. It is cheaper than the competition. The product solves the problem of time manipulating. To implement the necessary human, financial, information resources. Key partners will be Amazon Servers, Apple Store. Distribution and advertising of a product on the Internet and in the cities that will be served, buying contextual advertising. In the initial stages it will have to spend on advertising, development and maintenance. The costs include fees for advertising costs at the initial stage of development. <span style="color:blue">VIP-account</span> costs <span style="color:green">10$</span> a month. VIP includes smart notify and full history tasks, auto-entering necessary data.</p>
        </section>

        <footer>
           <p>Manipulating Time &copy; 2016</p>
        </footer>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Color</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.user_id %></td>
        <td><%= task.color %></td>
        <td><%= task.start_time %></td>
        <td><%= task.end_time %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @task.user_id %>
</p>

<p>
  <strong>Color:</strong>
  <%= @task.color %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @task.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @task.end_time %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<%= render 'layouts/header' %> 

<section id="content">
    <h1>Create your account</h1>
    	<%=form_for(@user) do |f| %>
    	<%= render 'shared/error_messages' %>
    		<div>
    		<%= f.label :name, "Name" %>
    		<%= f.text_field :name, :placeholder => "e.g. Egor Osokin", :class => "not_enter"%>
    		</div>
    		<div>
    		<%= f.label :email, "Email" %>
    		<%= f.text_field :email, :placeholder => "name@site.dom", :class => "not_enter"%>
    		</div>
    		<div>
    		<%= f.label :password, "Password" %>
    		<%= f.password_field :password, :placeholder => "Ajoqp01_q", :class => "not_enter" %>
    		</div>
    		<div>
    		<%= f.label :password_confirmation, "Confirm a password" %>
    		<%= f.password_field :password_confirmation, :class => "not_enter"%>
    		</div>
    		<div>
    		<%= f.submit "Create New Account" %>
    		</div>
		<% end %>
    </section>

    <footer>
        <p>Manipulating Time &copy; 2016</p>
    </footer>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name}") %>
<%= render 'layouts/header' %> 
<p id="notice"><%= notice %></p>
<section id="content">
    <p>Name: <%= @user.name %><p>
    	
   	<p>Email: <%= @user.email %><p>

    <%= link_to 'Edit', edit_user_path(@user) %> 
    <%= link_to "Sign out", signout_path, method: "delete" %>
    </section>

    <footer>
        <p>Manipulating Time &copy; 2016</p>
    </footer>